### ISSUE TITLE
How can I freeze intermiadiate layers in a model ?

### ISSUE THREAD

**Issue by shamanez** [aws-neuron/neuronx-distributed#16]
I am following the llama2 pre-training code. 

https://github.com/aws-neuron/neuronx-distributed/blob/main/examples/training/llama2/tp_zero1_llama2_7b_hf_pretrain/tp_zero1_llama2_7b_hf_pretrain.py

I do not understand how to freeze some of the parameters.

**Comment by aws-rhsoln** [comment]
Thank you for reporting the issue. For freezing weights, you can follow the same technique that one would follow for other torch models, need to set the `requires_grad` attr to false for the params that needs to be frozen.

**Comment by aws-rhsoln** [comment]
closing this issue, please re-open if the issue persists.
