### ISSUE TITLE
How to deal with LayerNorm or RMSNorm if I do TP

### ISSUE THREAD

**Issue by JH-ninjatech** [aws-neuron/neuronx-distributed#28]
Hi team,
I am doing tensor parallel tracing in `inf2.24xlarge` as the model size traced is over 16GB, which cannot be placed into one neuron core.
I now have a case where I need to normalize query and key right after I apply `ColumnParallelLinear` to `to_q` and `to_k` linear functions. How can I solve this issue?

**Comment by jeffhataws** [comment]
Hi @JH-ninjatech , thanks for reaching out. 

If you are applying normalization along the head dimension, you can compute normalization within each rank without performing a collective call. If you are applying normalization across heads, then you would have to share rank-local normalization statistics across ranks using a collective.
